Ext 231
scandiweb-extensions/bluecheck-age-verify-spwa pull request #1
Opened 2022-02-09 01:00 UTC by Lestaf-Pimentel

Solved EXT-231 passing Bluecheck's configuration to onShippingSuccess, which contains the shipping fields as arguments, during debugging also soved 244.

In regards to 244, added a check on component update which analyzed the instance's current state with the past one and reloaded the script when going from billing to shipping step.

There was also a bug when reloading the page that caused componintDidUnmount to attempt deletion when the script was not yet present, displaying an error message, so that was fixed as well.

2022-02-09 09:33 UTC, GAkim requested changes

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +//import { connect } from 'react-redux';
remove commented code

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +//import blueCheckScriptEnabler from '../../../static/blueCheckEnablerScript';
remove commented code

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +    console.log("WHAEIHIFqmNAK")
remove console.logs

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +    console.log('AAAAAAAAAA')
remove console.logs

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +    console.log(BlueCheck)
remove console.logs

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +                        //e.stopPropagation();
remove commented code

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +                console.log(verifyBtn);
remove console.logs

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +//keeping this for posterity
remove this lines

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +    console.log('scraping...', email);
remove console log

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +    //const country = document.getElementById('country_id');
remove commented code

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +    //const region = document.getElementById('region_id');
remove comented code

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +    console.log(BlueCheck.userData);
remove log

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +    console.log('starting...');
remove log

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +            console.log(verifyBtn);
remove log

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +            console.log('listening forcheckout')
remove loging

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +        console.log('StartedScarping')
remove loging

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +            ? /*scrapeLoggedInUserData(addresses, email)*/console.log("weeee") : console.log("WAAAA")//scrapeGuestUserData(email);
remove comented code

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/static/blueCheckEnablerScript.js
> +    console.log("O O BUBU",BlueCheck)
remove loging

2022-02-09 09:33 UTC, GAkim commented on pwa/packages/bluecheckageverify-spwa/src/plugin/route/Checkout/CheckoutContainer.plugin.js
> +
no need in to blank lines

2022-02-09 12:41 UTC, Lestaf-Pimentel commented
Fixed formatting problems, deleted redundant file

2022-02-10 06:03 UTC, GAkim approved these changes

2022-02-15 17:54 UTC, merged